#!/bin/bash

# See file COPYING distributed with the xnnppx package for the copyright 
# and license.

pipeline_home=/home/vmuser/xnat/pipeline

xml=`echo "$@" | tr ' ' '\n' | grep -A 1 -e '-pipeline' | tail -1`
py=`echo "$xml" | sed 's/xml$/py/'`

if [ -f $py ]
then
    $pipeline_home/bin/XnatPythonLauncher "$@"
else
    $pipeline_home/bin/XnatPipelineLauncher.orig "$@"
fi

exit $?

# eof
